import mysql.connector

conn = mysql.connector.connect(
    host='localhost',
    user='root',
    password='password'
)

cursor = conn.cursor()
create_database_query = "Create DATABASE name_of_db"
cursor.execute(create_database_query)
cursor.close()
conn.close()

'''some extra queries:
 
 
 
 
 
 
 /*
to insert new data
INSERT INTO orders (customer_id, total_amount, payment_method, tax_id)
VALUES (1, 25.00, 'Card', 2);
INSERT INTO order_details (order_id, product_id, quantity, price, discount_percentage, tax_percentage)
VALUES (1, 2, 3, 0.00, 0.00, 0.00), (1, 4, 2, 0.00, 0.00, 0.00); 
INSERT INTO payments (order_id, payment_method, amount)
VALUES (1, 'Card', 25.00);*/

/*
-- to find total products sold
select p.name, sum(od.quantity) as quantity
from products as p
join order_details as od on p.product_id = od.product_id
group by p.name;*/

/*
-- total profit
select sum((od.price - p.cost) * od.quantity) as profit
from order_details od
join products p on od.product_id = p.product_id
*/

/*
-- finding total tax deducted
select sum(od.quantity * (od.price - (od.price / (1 + od.tax_percentage / 100)))) as total_tax
from order_details as od
*/

/*
-- customers over 15 purchasing kids meal
select count(distinct o.customer_id) as yak_customers
from orders o
join order_details od on o.order_id = od.order_id
join products p on od.product_id = p.product_id
join customers c on o.customer_id = c.customer_id
where c.age > 15 and p.meal_type = 'Kids Meal';
*/

/*
-- most famous product
select p.name, sum(od.quantity) as max
from products as p
join order_details as od on p.product_id = od.product_id
group by p.name
order by max desc limit 1*/


/*
-- Revenue by each Product
select p.name, sum(od.price)*sum(od.quantity) as revenue
from products as p
join order_details as od on p.product_id = od.product_id
group by p.name
*/


/* to quantity sold per product
select p.name, sum(od.quantity) as quantity
from products as p
join order_details as od on p.product_id = od.product_id
group by p.name*/

/*
-- total revenue generated by each payment
SELECT 
    o.payment_method, 
    SUM(od.quantity * (od.price + (od.price * (od.tax_percentage / 100)))) AS total_revenue
FROM 
    orders o
JOIN 
    order_details od ON o.order_id = od.order_id
GROUP BY 
    o.payment_method;
*/
/*
select sum(od.quantity),p.name
from order_details as od
join products as p on p.product_id= od.product_id
group by p.name
*/

/*
-- How many orders has each customer placed?
select count(od.order_id) as  no_of_oders, c.first_name
from order_details as od
join customers as c on c.customer_id= od.customer_id
group by c.first_name
*/

/*
-- Which products have had a discount applied and what are the discount percentages?
select p.name,od.discount_percentage
from products as p
join order_details as od on od.product_id=p.product_id
where discount_percentage>0.0
*/

/*
-- top 5 customers
select c.first_name,sum(o.total_amount) as spends
from orders as o
join customers as c on c.customer_id = o.customer_id
group by c.first_name
order by c.first_name desc limit 5
*/

 
 
 
 
 
 
 
 
 
 
 
 '''
